server:
  session:
    timeout: 1800
  port: 8088
zhiyou:
  upload:
    url: D:/apache-tomcat-7.0.70/webapps/upload/jump
    visit: http://192.168.1.166:9080/upload/jump
  logoutUri: redirect:/login
logging:
  level:
    root: WARN
    com.zhiyou.jump: WARN
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.254:3306/jump_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password : root
  redis:
      host: 192.168.1.254
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        maxIdle: 8
        # 连接池中的最小空闲连接
        minIdle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        maxActive: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxWait: -1
c3p0:
  driverClass: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://192.168.1.254:3306/jump_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
  user: root
  password: root
  minPoolSize: 5
  maxPoolSize: 20
  maxIdleTime: 60
  acquireIncrement: 5
  maxStatements: 0
  initialPoolSize: 10
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: true
  testConnectionOnCheckout: false